package com.codewithmosh.store.entities;

import com.codewithmosh.store.Payments.PaymentStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
@Getter
@Setter
@Entity
@Table(name = "orders")
public class Order {

    @Column(name = "id")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "customer_id")
    private User customer;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private PaymentStatus status;

    @Column(name = "created_at",insertable = false,updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "total_price")
    private BigDecimal totalPrice;

    @OneToMany(mappedBy = "order",cascade = {CascadeType.PERSIST,CascadeType.REMOVE})
    private Set<Order_Items> items = new HashSet<>();

    public static Order fromCart(Cart cart,User customer)
    {
        var order = new Order();
        order.setTotalPrice(cart.getTotalPrice());
        order.setStatus(PaymentStatus.PENDING);
        order.setCustomer(customer);
        cart.getItems().forEach(item->
                {

                    order.items.add(new Order_Items(order,item.getProduct(),item.getQuantity()));
                }
        );
        return order;
    }

    public  boolean isPlacedBy(User customer)
    {
        return this.customer.equals(customer);   //customer.getId().equals(customer.getId()) //violating information expert principle
       //here we are using the equals method generated by the @EqualsAndHash annotation based on the id since both this.customer and passed customer is User object so both id will be matched in the equals method.
    }
}
